version: '3.9'

services:
  backend_app:
    container_name: node_app
    build:
      context: .
    ports:
      - 5002:5002
    volumes:
      - $PWD/logs:/home/node/app/logs
    env_file:
      - ./.env
    environment:
      - PORT=5002
      - migrateDevArg=1
      - PG_DB_HOST=postgress_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: always
    depends_on:
      - postgress_db
    command: sh -c './entrypoint.sh'
  postgress_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
    volumes:
      - pg_db:/var/lib/postgresql/data
    ports:
      - 5435:5432
volumes:
  pg_db:
    driver: local
